name: scf_dev
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.1=py_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2020.4.5.1=py38h32f6830_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_1000
  - expat=2.2.9=he1b5a44_2
  - fbpca=1.0=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py38h6f030ca_1002
  - gmp=6.2.0=he1b5a44_2
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=64.2=he1b5a44_1
  - igraph=0.7.1=h9e3b1fc_1007
  - importlib_metadata=1.5.0=py38_0
  - ipykernel=5.1.4=py38h5ca1d4c_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py38_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_client=5.3.4=py38_1
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py38_0
  - jupyter_core=4.6.3=py38_0
  - jupyter_highlight_selected_word=0.2.0=py38_1000
  - jupyter_latex_envs=1.4.6=py38_1000
  - jupyter_nbextensions_configurator=0.4.1=py38_0
  - jupyterlab=1.2.6=py_0
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py38hc9558a2_0
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - leidenalg=0.7.0=py38he1b5a44_1
  - libblas=3.8.0=15_openblas
  - libcblas=3.8.0=15_openblas
  - libclang=9.0.1=default_hde54327_0
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=15_openblas
  - libllvm8=8.0.1=hc9558a2_0
  - libllvm9=9.0.1=hc9558a2_0
  - libopenblas=0.3.8=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - llvm-openmp=9.0.1=hc9558a2_2
  - llvmlite=0.31.0=py38h8b12597_0
  - lxml=4.5.0=py38hbb43d70_1
  - markupsafe=1.1.1=py38h516909a_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h250f245_0
  - mistune=0.8.4=py38h516909a_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - notebook=6.0.3=py38_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numba=0.48.0=py38hb3f55d8_0
  - numpy=1.18.1=py38h95a1406_0
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.1=py38hb3f55d8_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycairo=1.19.1=py38h438ddbb_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py38hcca6a23_1
  - pyrsistent=0.15.7=py38h516909a_0
  - python=3.8.1=h357f687_2
  - python-dateutil=2.8.1=py_0
  - python-igraph=0.8.0=py38h9e3b1fc_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - pyzmq=18.1.1=py38h1768529_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - scikit-learn=0.22.1=py38hcdab131_1
  - scipy=1.4.1=py38h921218d_0
  - seaborn=0.10.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.30.1=hcee41ef_0
  - statsmodels=0.11.1=py38h516909a_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - texttable=1.6.2=py_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.3=py38h516909a_4
  - traitlets=4.3.3=py38_0
  - umap-learn=0.3.10=py38_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.4=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - pip:
    - annoy==1.16.3
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1

